In [1]:
import numpy as np

In [ ]:
np.full((3, 3), 2)

In [ ]:
np.random.seed(0)
Q2 = np.random.randint(10, size =(3, 4)) #creating random array
Q3 = Q2[1:2, 1:3] #slicing and indexing the array
Q4 = Q2[2:3, :3]
Q5 = Q2[1:2, 1:4]
Q6 = Q2[:1, :1]
Q7 = Q2[1:2, :1]
Q8 = Q2[2:3, :1]
print(Q2)
print(Q3)

In [5]:
Q2_sub = Q2[:2, :2]
print(Q2_sub)

[[5 0]
 [7 9]]


In [6]:
Q2_sub[0,0] = 99
print(Q2_sub)

[[99  0]
 [ 7  9]]


In [ ]:
Q2

array([[99,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

In [7]:
Q2_sub_copy = Q2[:2, :2].copy()
print(Q2_sub_copy)

[[99  0]
 [ 7  9]]


In [8]:
Q2_sub_copy[0,0] = 42  #creating a copy of Q2 to manipulate without altering original data
print(Q2_sub_copy)

[[42  0]
 [ 7  9]]


In [9]:
Q2

array([[99,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

In [10]:
array = np.arange(1, 10) #arraning data by number including 1-9
print(array)

[1 2 3 4 5 6 7 8 9]


In [11]:
grid = array.reshape((3,3)) #Reshaping in grid method
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
array2 = np.arange(1,11)
grid2 = array2.reshape((5,2))
print(grid2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [16]:
t = np.array([1, 2, 3])
print(t)

[1 2 3]


In [17]:
t.reshape((1,3)) # reshaping arrays

array([[1, 2, 3]])

In [18]:
t[np.newaxis, :] #creating new axis point

array([[1, 2, 3]])

In [19]:
t[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [20]:
t.reshape((3,1))

array([[1],
       [2],
       [3]])

In [21]:
np.random.seed(0)
x = np.random.randint(5, size = (4, 4))
print(x)

[[4 0 3 3]
 [3 1 3 2]
 [4 0 0 4]
 [2 1 0 1]]


In [22]:
np.random.seed(56)
x = np.random.randint(20, size = (10, 10))
print(x)

[[ 4 15  0  2 11 14  9  4 15 17]
 [12  2 11 11 14 16  6  1 10  5]
 [ 2 15 19  5  9  2 10  1 16 13]
 [ 6 18 12  0  8  4 14 15  0 17]
 [11 17 12 19 14 10 18  1 19  3]
 [ 2  0  3 16 16  8 16  9 11  0]
 [10 18 19  7  1 11  5 16  8  2]
 [13  8 16 19 18  7 18  5 16 14]
 [17  1  7 15  4  1 19  2  0  8]
 [15 16  5 19  7  7  0 15  1 19]]


In [23]:
x[2:3, 4:5]

array([[9]])

In [24]:
np.random.seed(1)
x = np.random.randint(15, size = 10)
y = np.random.randint(15, size = 10)

print(x)
print(y)

[ 5 11 12  8  9 11  5  0  0  1]
[12  7 13 12  6  9  2  4 14  5]


In [26]:
x.reshape((2,5))

array([[ 5, 11, 12,  8,  9],
       [11,  5,  0,  0,  1]])

In [29]:
x_sub  = x[:2].copy()
print(x_sub)

[ 5 11]


In [30]:
np.random.seed(0)
x = np.random.randint(0,15, size = 10)
y = np.random.randint(0,15, size = 10)
Q5 = np.concatenate([x,y]) #concatenating the random numbers list
print(Q5)

[12  5  0  3 11  3  7  9  3  5  2  4  7  6  8  8 12 10  1  6]


In [31]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y])  #concatenating the one dimensional arrays

array([1, 2, 3, 4, 5, 6])

In [32]:
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
x = np.array([7, 8, 9])
np.vstack([x, grid]) #vertical stacking the previous arrray onto the new array

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2 = np.split(x, [3]) #splitting the array
print(x1, x2)

[0 1 2] [3 4 5 6 7 8 9]


In [36]:
np.random.seed(0)
Q8 = np.random.randint(48,86, size = 50)
Q8 = np.mean(Q8) #calculating the mean of the values

In [37]:
name = ['Jonathan Loaisiga', "Nick Saban", 'Katie Ladecky']
occupation = ['Baseball player', 'Football coach', 'Swimmer']
salary = [595800.00, 8619934.23, 100000.00]  #creating lists to use in df

In [38]:
Q6 = np.zeros(3, dtype = {'names' :('name', 'occupation', 'salary'),
                            'formats' :('U20', 'U20', 'f8')})
#creatign structured arrays with specific data type using the dtype parameter
print(Q6.dtype)

[('name', '<U20'), ('occupation', '<U20'), ('salary', '<f8')]


In [39]:
Q6['name'] = name
Q6['occupation'] = occupation
Q6['salary'] = salary
#assignig corresponding fileds in the structured arrays which contains the data within the lists
print(Q6)

[('Jonathan Loaisiga', 'Baseball player',  595800.  )
 ('Nick Saban', 'Football coach', 8619934.23)
 ('Katie Ladecky', 'Swimmer',  100000.  )]


In [44]:
q1 = {
    "One": "A",
    "Two": "B",
    "Three": "C",
    "Four": "D"
}
#creating a dictionary with Keys and mapping their corresponding value
print(q1["Four"])

D


In [45]:
def Q6(q1):
  for i in q1:
    #printing the key in a dictionary
    print(i)
Q6(q1)

One
Two
Three
Four


In [46]:
def Q5(q1):
  for i in q1:
    #printing the value in a dictionary
    print(q1[i])
Q5(q1)

A
B
C
D


In [47]:
x = np.arange(10)

i = np.array([2, 1, 8, 4])
x[i] = 99
#updating indices and replacing its value to random number
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [50]:
np.random.seed(1)
x = np.random.randint(10, size = (4,4))
print(x)

x[1:3, 0:3]

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]]


array([[0, 0, 1],
       [6, 9, 2]])

In [51]:
np.random.seed(1)
x = np.random.randint(10, size = (4, 4))
print(x)
#selecting rows 1 and 2 and colums 0-2 to create subarray
x[1:3, 0:3]

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]]


array([[0, 0, 1],
       [6, 9, 2]])

In [52]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[3:6]

array([3, 4, 5])